### ISSUE TITLE
Prepare for upcoming data format change in content-proxy for steps.json

### ISSUE THREAD

**Issue by tripodsan** [adobe/pages#1]
https://github.com/davidnuescheler/pages/blob/ce9194e1bc74b0901625ddd3c2dedac795005563/scripts/twp3.js#L4-L7

see https://github.com/adobe/helix-content-proxy/issues/121

**Comment by davidnuescheler** [comment]
haha... very good! i was just mentioning this to @ispykenny today.
do you have an ETA on that?

**Comment by davidnuescheler** [comment]
like this?

https://github.com/davidnuescheler/pages/blob/staging/scripts/twp3.js#L4-L8
