### ISSUE TITLE
[Enhancement request] Add Marquee block to default Pages block library (or, enhance existing Hero block)

### ISSUE THREAD

**Issue by timliu-adobe** [adobe/pages#415]
**Note:** I'm not sure if the more logical enhancement is to port over the Marquee block from Consonant to the default Pages blocks, or to enhance the existing Hero block with a new functionality; please let me know, and I can update this ticket to reflect the planned course of action. I think either would work for my desired use case.

### Expected Behaviour

I'd like to create a Marquee/hero section on my form landing page that looks like this:

<img width="1152" alt="Screen Shot 2022-01-10 at 6 44 46 PM" src="https://user-images.githubusercontent.com/91575950/148872453-85abb78a-f796-41e7-90e5-3b936180db25.png">

The icon/logo, header, and copy should all be centered in the marquee/hero image (in this case, the black banner with the rainbow trim). That asset can be found here:

![CCX_Registration_HeroImg_2x](https://user-images.githubusercontent.com/91575950/148872560-865bde9d-8828-4246-9000-e152ecb81d7d.jpg)

### Actual Behaviour

There are two ways I've tried to produce this, but neither works how I'd like it to:

**Version 1: using the default Hero block**

This is what my page looks like in Helix:
<img width="790" alt="Screen Shot 2022-01-10 at 6 52 44 PM" src="https://user-images.githubusercontent.com/91575950/148873025-9cd3d706-2a23-414d-bcd3-b882ba7f7d20.png">

This is what it renders like:
<img width="957" alt="Screen Shot 2022-01-10 at 6 52 06 PM" src="https://user-images.githubusercontent.com/91575950/148873081-aa62b0b3-0eca-4046-8214-51a13c43fcad.png">

The black banner is placed on _top_ of the Logo/Header/Copy instead of being the background. In addition, my form does not render properly. The desired enhancement for this version would be to have the Hero block support a background banner (so that the banner serves as the background for the Logo/Header/Copy. The Logo/Header/Copy should remain centered-justified.

**Version 2: using the Consonant template's Marquee block**

An alternative approach was using the Consonant template library's Marquee block (reference example [here](https://main--pages--webistry-development.hlx3.page/stock/en/artisthub/drafts/artisthub-2.2/)). My Helix page looked like this:

<img width="610" alt="Screen Shot 2022-01-10 at 6 55 51 PM" src="https://user-images.githubusercontent.com/91575950/148873366-81f031c2-31c8-4454-8c65-a41bc6037b8b.png">

But it rendered like this:
<img width="1612" alt="Screen Shot 2022-01-10 at 6 49 26 PM" src="https://user-images.githubusercontent.com/91575950/148873401-9d09c319-d5d9-4859-b911-0f200ca4ffe9.png">

The black hero/marquee banner behaves correctly here, but there are still issues; the spacing between the logo and header is way too large, the Logo/Header/Copy is all left justified instead of center-justified, and most importantly, the form does not render at all (and the form format doesn't seem to be recognized, as indicated by the strings of text on the preview). A potential other solution would be to port this Marquee block over to the default Pages block library so that the page can still read forms.

**I reviewed these two scenarios with Sean Choi, and it seemed to us that an enhancement to the Hero block to support a background marquee image would probably be easier. But either of the two would be great for what I'm looking for, so happy to defer to the Dev's opinion.**

### Reproduce Scenario (including but not limited to)

My test pages can all be found in this folder: https://drive.google.com/drive/u/1/folders/1lNBMLjx2ca2LDdbcjp7ylrVDFV8Z468e

"Express-your-brand" and "Express-your-brand-2" are the two test pages. Two sample forms are also in the folder for testing.

#### Steps to Reproduce

1. Open either "Express-your-brand" or "Express-your-brand-2"
2. Try to load the page using Helix sidekick

#### Platform and Version

N/A

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

N/A

**Comment by ispykenny** [comment]
Hey @timliu-adobe, 

This block has been implemented. [Take a look here](https://pages.adobe.com/cc-growth-sandbox/test/blocks)
Marking this as resolved!
